dev: fix justfile integration-test recipe
integration-test recipe used build-integration-test as a dependency, but
after dependency is executed (or if it doesn't run) the integration-test
recipe failed because it didn't source the environment by itself:

```
$ just integration-test
...
invoke tests
sh: 1: invoke: not found
error: Recipe `integration-test` failed on line 189 with exit code 127
```

This commit duplicates the shebang from build-integration-test to
integration-test so that the recipe works again. I'm not sure if there's
a way to avoid the copy paste though, if there is, hopefully somebody
mentions it in the review.

Signed-off-by: Marcel Guzik <marcel.guzik@cumulocity.com>