Fix tedge cert renew error-prone error message
When run without enough privileges
`tedge cert renew` was returning an error-prone message:

```
A private key already exists and would be overwritten.
Run `tedge cert remove` first to generate a new certificate and private key.
```

With this fix the error points to the correct cause:

```
Error: failed to renew the device certificate from https://127.0.0.1

Caused by:
    0: I/O error accessing the private key: "/etc/tedge/device-certs/demo-device-888.key"
    1: Permission denied (os error 13)
```

Signed-off-by: Didier Wenzek <didier.wenzek@free.fr>