Soft-revert "cryptoki: call C_Initialize for every session"
Disable the slot refresh fix and ignore its test suite.

We do this because in the user's environment, using a Nitrokey HSM,
reloading the library is too slow and leads to hitting a TLS timeout and
getting a TLS close_notify error:

error: Connection error while creating device in Cumulocity: Mqtt state: Mqtt serialization/deserialization error: IO: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof: Mqtt serialization/deserialization error: IO: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof: IO: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof: peer closed connection without sending TLS close_notify: https://docs.rs/rustls/latest/rustls/manual/_03_howto/index.html#unexpected-eof

This is the same error that TedgeP11Client::with_ready_check prevents,
but the slot fix makes it reappear on that environment. As the slot
issue concerns only softhsm which probably isn't used in any production
environments, for now we revert this fix until we solve more pressing
issues, i.e. #3766.

Signed-off-by: Marcel Guzik <marcel.guzik@cumulocity.com>