tedge-p11-server: try to load cryptoki lib immediately
If the cryptoki dynamic module doesn't exist or loading it causes some
other error, then we exit with an error immediately since we can't
handle any requests.

Notably, when module path is wrong, the process exits with the following
message:

Error: Failed to start the signing service

Caused by:
    0: Failed to get handle of pkcs11 signing key
    1: Failed to load PKCS#11 dynamic object
    2: /lib/x86_64-linux-gnu/libykcs.so: cannot open shared object file: No such file or directory

Signed-off-by: Marcel Guzik <marcel.guzik@cumulocity.com>